### ISSUE TITLE
[BUG] No windows compatibility

### ISSUE THREAD

**Issue by Engwer** [NYSCF/ScaleFEx#53]
I wanted to clone the repository on Windows, but got some errors due to incompatible file names, namely:

- `sample_data/output/Dataset01_2024-08-14 08:56:26.455525_coordinates.csv`
- `sample_data/output/Dataset01_2024-08-14 08:56:26.455525_parameters.csv`

To fix this, I suggest to omit `:` from the filename and change the following line:

https://github.com/NYSCF/ScaleFEx/blob/54e439a5ca7c2d3747a88523a087099fc33957b4/scalefex_main.py#L47

into:

```python
start_time = datetime.now().strftime("%Y-%m-%d %H%M%S")
```

**Comment by winch-jm** [comment]
Hi @Engwer, thanks for pointing this out! I will fix this today

**Comment by Engwer** [comment]
Thanks for replying so quickly. I saw in your PR #54 that `scalefex_main.py` was changed but the corresponding files in `sample_data` were not. Will they be updated automatically? If not, cloning on Windows will still fail.

**Comment by winch-jm** [comment]
I see what you mean; this will be fixed momentarily. The majority of our testing has been on Linux, and there is still some testing to be done on Windows. 

Thanks for your patience!
